//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addmin
    {
        public int IdAd { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<int> YearBirth { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    }
}
