//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHD
    {
        public int IdHD { get; set; }
        public int IdSp { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<decimal> Tien { get; set; }
        public string Size { get; set; }
    
        public virtual ChiTietSp ChiTietSp { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
