//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
        }
    
        public int IdHD { get; set; }
        public Nullable<int> IdKh { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> IdDH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
        public virtual DatHang DatHang { get; set; }
        public virtual DatHang DatHang1 { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
