//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShopEntities : DbContext
    {
        public ShopEntities()
            : base("name=ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addmin> Addmins { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<ChiTietDH> ChiTietDHs { get; set; }
        public virtual DbSet<ChiTietHD> ChiTietHDs { get; set; }
        public virtual DbSet<ChiTietSp> ChiTietSps { get; set; }
        public virtual DbSet<DatHang> DatHangs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<SanPham_Anh> SanPham_Anh { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int InsertDatHang(Nullable<int> idKh, string name, Nullable<decimal> sDT, string diaChi, string tinhThanh, string quanHuyen, string phuongXa, string ghiChu)
        {
            var idKhParameter = idKh.HasValue ?
                new ObjectParameter("idKh", idKh) :
                new ObjectParameter("idKh", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(decimal));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var tinhThanhParameter = tinhThanh != null ?
                new ObjectParameter("TinhThanh", tinhThanh) :
                new ObjectParameter("TinhThanh", typeof(string));
    
            var quanHuyenParameter = quanHuyen != null ?
                new ObjectParameter("QuanHuyen", quanHuyen) :
                new ObjectParameter("QuanHuyen", typeof(string));
    
            var phuongXaParameter = phuongXa != null ?
                new ObjectParameter("PhuongXa", phuongXa) :
                new ObjectParameter("PhuongXa", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertDatHang", idKhParameter, nameParameter, sDTParameter, diaChiParameter, tinhThanhParameter, quanHuyenParameter, phuongXaParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<Product_Hot_Result> Product_Hot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product_Hot_Result>("Product_Hot");
        }
    
        public virtual ObjectResult<product_HotID_Result> product_HotID(Nullable<int> idlsp)
        {
            var idlspParameter = idlsp.HasValue ?
                new ObjectParameter("idlsp", idlsp) :
                new ObjectParameter("idlsp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<product_HotID_Result>("product_HotID", idlspParameter);
        }
    
        public virtual ObjectResult<SanPham_Cart_Result> SanPham_Cart(Nullable<int> idKh)
        {
            var idKhParameter = idKh.HasValue ?
                new ObjectParameter("idKh", idKh) :
                new ObjectParameter("idKh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanPham_Cart_Result>("SanPham_Cart", idKhParameter);
        }
    }
}
